<?php
/**
 * comyo.media
 * @link http://www.comyo-media.de
 * Projekt: Error Pages - YaS Online
 * @link $ProjectUrl$
 *
 * @author "David Marner" <marner@comyo-media.de>
 * @created 16.03.13 - 22:17
 */
?>
<div class="hero-unit">
    <h1>Congratulations!</h1>
    <p>Well good job <strong class="text-info">Mr. Detective</strong>, you found the internal page.</p>
    <p><small>Still i knew you would come here.</small></p>
</div>
<?php include 'templates/credits.phtml'; ?>
