<?php
/**
 * comyo.media
 * @link http://www.comyo-media.de
 * Projekt: Error Pages - YaS Online
 * @link $ProjectUrl$
 *
 * @author "David Marner" <marner@comyo-media.de>
 * @created 16.03.13 - 22:11
 */
?>
<footer>
    <p class="pull-right">
        <img src="/img/logo_2012_exact.png" alt="logo" style="max-height: 85px">
    </p>
    <p>&copy; YaS Online 2004 - <?php echo date('Y'); ?> by
        <a href="mailto:marner@comyo-media.de">David Marner</a> &amp;
        <a href="mailto:neico@yas-online.net">Nicolas Hamm</a>
    </p>
</footer>
